version: '3.3'
services:

  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot # Troque se necessario
      - POSTGRES_PASSWORD=typebot # Troque se necessario
  typebot-builder:
    labels:
      virtual.host: 'fluxo.systemhelp.site' # Troque pelo seu dominio ou subdominio
      virtual.port: '3000'
      virtual.tls-email: 'system.help.tutoriais@gmail.com' # Troque pelo seu email
    image: elestio/typebot-builder:latest
    restart: always
    ports:
      - '3001:3000'
    depends_on:
      - typebot-db
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=https://fluxo.systemhelp.site # Troque pelo seu dominio ou subdominio
      - NEXT_PUBLIC_VIEWER_URL=https://fluxo.bot.systemhelp.site # Troque pelo seu dominio ou subdominio
      - ENCRYPTION_SECRET=c56f3775313440c3edce57529a0f02b4
      - ADMIN_EMAIL=system.help.tutoriais@gmail.com # Troque pelo seu email
      #- DISABLE_SIGNUP=false # Mude Para false caso queira permitir que outras pessoas criem contas
      - SMTP_AUTH_DISABLED=false
      - SMTP_SECURE=false # Troque para false seu nao usar a porta 465 ou se estiver enfretando problemas no login
      - SMTP_HOST=smtp.gmail.com # Troque pelo seu SMTP USE SOMENTE DOMINIO PROPRIETARIOS
      - SMTP_PORT=587 # altere aqui se nescessario portas comuns 25, 587, 465, 2525
      - SMTP_USERNAME=system.help.tutoriais@gmail.com # troque pelo seu email
      - SMTP_PASSWORD=dykyhanmtiddrzoj # Troque pela sua senha
      - NEXT_PUBLIC_SMTP_FROM=system.help.tutoriais@gmail.com # Troque pelo seu email
      - S3_ACCESS_KEY=minio # Troque se necessario
      - S3_SECRET_KEY=minio123 # Troque se necessario
      - S3_BUCKET=typebot
      - S3_ENDPOINT=fluxo.memoria.systemhelp.site # Troque pelo seu dominio ou subdominio
  typebot-viewer:
    labels:
      virtual.host: 'fluxo.bot.systemhelp.site' # Troque pelo seu dominio ou subdominio
      virtual.port: '3000'
      virtual.tls-email: 'system.help.tutoriais@gmail.com' # Troque pelo seu email
    image: elestio/typebot-viewer:latest
    restart: always
    ports:
      - '3002:3000'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=https://fluxo.systemhelp.site # Troque pelo seu dominio ou subdominio
      - NEXT_PUBLIC_VIEWER_URL=https://fluxo.bot.systemhelp.site # Troque pelo seu dominio ou subdominio
      - ENCRYPTION_SECRET=c56f3775313440c3edce57529a0f02b4
      - SMTP_HOST=smtp.gmail.com # Troque pelo seu SMTP USE SOMENTE DOMINIO PROPRIETARIOS
      - NEXT_PUBLIC_SMTP_FROM=system.help.tutoriais@gmail.com # Troque pelo seu email
      - S3_ACCESS_KEY=minio # Troque se necessario - Deve ser Igual ao Declarado no Typebot Builder S3_ACCESS_KEY=
      - S3_SECRET_KEY=minio123 # Troque se necessario - Deve ser Igual ao Declarado no Typebot Builder S3_SECRET_KEY=
      - S3_BUCKET=typebot
      - S3_ENDPOINT=fluxo.memoria.systemhelp.site # Troque pelo seu dominio ou subdominio
  mail:
    image: bytemark/smtp
    restart: always
  minio:
    labels:
      virtual.host: 'fluxo.memoria.systemhelp.site' # Troque pelo seu dominio ou subdominio
      virtual.port: '9000'
      virtual.tls-email: 'system.help.tutoriais@gmail.com' # Troque pelo seu email
    image: minio/minio
    command: server /data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: minio # Troque se necessario - Deve ser Igual ao Declarado no Typebot Builder S3_ACCESS_KEY=
      MINIO_ROOT_PASSWORD: minio123 # Troque se necessario - Deve ser Igual ao Declarado no Typebot Builder S3_SECRET_KEY=
    volumes:
      - s3_data:/data
  # This service just make sure a bucket with the right policies is created

  # Certifique-se de atualizar S3_ACCESS_KEY , S3_SECRET_KEY abaixo para corresponder às suas configurações do S3, elas estão no final dessa linha /usr/bin/mc config host add minio http://minio:9000 minio minio123; sendo o usuario e a senha em sequencia.
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;
      "
volumes:
  db_data:
  s3_data:
  caddy-certificates:
    driver: local

